spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/member
    username: root
    password: 1234
  jpa:
    properties:
      hibernate:
        show_sql: true
        globally_quoted_identifiers: true
        format_sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 3b9c8d8b1c4998931071
            client-secret: 6bedf9cda01c141cfce78137c8ba1ed568dcb75d
          google:
            client-id: your-app-client-id
            client-secret: your-app-client-secret
          spring:
            client-id: your-app-client-id
            client-secret: your-app-client-secret

logging:
  level:
    root: debug

server:
  port: 8080
